package de.adesso.tools.ui;

/**
 * Created by mohler on 23.01.16.
 */
public enum Notifications {

    ADD_CONDITION, INS_CONDITION, REM_CONDITION,
    ADD_ACTION, INS_ACTION, REM_ACTION,
    ADD_RULE, INS_RULE, REM_RULE, REM_RULES_WITHOUT_ACTIONS,
    PREPARE_CONSOLE, MOVE_ACTION_DECL_UP, MOVE_ACTION_DECL_DOWN,
    MOVE_RULE_LEFT, MOVE_RULE_RIGHT, MOVE_COND_DECL_DOWN,
    MOVE_COND_DECL_UP, ADD_ELSE_RULE,
    FILE_OPEN, FILE_SAVE_AS, EV_CONSOLIDATE_RULES;
}
